const { Client } = require('pg');

const connectionString = 'postgresql://postgres:Glps162487$@db.rgqawadlrhzwgfagnrmy.supabase.co:5432/postgres';
const client = new Client({ connectionString, ssl: { rejectUnauthorized: false } });

const PRODUCTS = [
  { slug: 'zapmax', name: 'ZapMax CRM', category: 'WhatsApp', short_description: 'Plataforma multiatendimento com chatbot inteligente e funis de vendas.', long_description: 'O ZapMax CRM é a solução definitiva para centralizar o atendimento no WhatsApp de qualquer empresa.', price: 297, rating: 4.9, sales_count: 1420, badge: 'MAIS VENDIDO', features: ['Múltiplos atendentes em um só número','Chatbot visual Drag & Drop','Disparos em massa inteligentes','Integração direta via Webhook/API','Relatórios de desempenho da equipe'], tech_stack: ['Node.js','React','TypeScript','Prisma','Socket.io'], gradient: 'from-green-500/20 via-emerald-600/35 to-brand-black', icon_name: 'MessageSquare', active: true },
  { slug: 'titanops', name: 'TitanOps SaaS', category: 'SaaS', short_description: 'ERP para automação de processos internos e gestão operacional escalável.', long_description: 'Automatize todas as operações internas de negócios em um único local.', price: 499, rating: 4.8, sales_count: 890, badge: 'HOT', features: ['Gerenciamento de tarefas Kanban & Gantt','Faturamento recorrente integrado','Módulo de suporte ao cliente com tickets','Templates de automação de fluxo','Suporte multi-empresa'], tech_stack: ['Next.js','PostgreSQL','TailwindCSS','Go','Redis'], gradient: 'from-blue-600/20 via-indigo-600/30 to-brand-black', icon_name: 'Layers', active: true },
  { slug: 'delivery-pro', name: 'Delivery PRO', category: 'Delivery', short_description: 'Sistema completo de pedidos online com cardápio digital e integração WhatsApp.', long_description: 'Uma plataforma whitelabel de ponta para restaurantes.', price: 197, rating: 4.7, sales_count: 1105, badge: 'HOT', features: ['Cardápio digital interativo e responsivo','Notificações de status de pedido por WhatsApp','Calculadora automática de rota e frete','Integração com impressoras térmicas (ESC/POS)','Painel de cupons e promoções'], tech_stack: ['React','NestJS','PostgreSQL','TailwindCSS','Firebase'], gradient: 'from-brand-orange/20 via-red-600/30 to-brand-black', icon_name: 'ShoppingBag', active: true },
  { slug: 'builderfy-ai', name: 'Builderfy AI', category: 'IA', short_description: 'Crie landing pages, sites e funis de vendas completos em segundos usando IA.', long_description: 'O Builderfy AI revoluciona a criação de páginas.', price: 349, rating: 4.95, sales_count: 954, badge: 'IA', features: ['Geração de layouts via comando de voz ou texto','Criação de copywriting persuasivo inclusa','Hospedagem global ultrarrápida integrada','Exportação direta para HTML/React','Integração de formulários nativa'], tech_stack: ['Next.js','OpenAI API','Framer Motion','TailwindCSS','Supabase'], gradient: 'from-purple-500/20 via-pink-600/30 to-brand-black', icon_name: 'Sparkles', active: true },
  { slug: 'clinica-pro', name: 'Clínica PRO', category: 'Dashboard', short_description: 'Painel administrativo avançado para gestão médica e agendamentos online.', long_description: 'Desenvolvido especificamente para médicos, dentistas e clínicas de saúde.', price: 389, rating: 4.8, sales_count: 620, badge: null, features: ['Agenda inteligente multi-profissional','Prontuário eletrônico criptografado','Lembrete automático de consulta via WhatsApp','Módulo financeiro integrado','Telemedicina com videochamada criptografada'], tech_stack: ['React','Express','MongoDB','Node.js','WebRTC'], gradient: 'from-cyan-500/20 via-teal-600/30 to-brand-black', icon_name: 'Activity', active: true },
  { slug: 'agencia-pro', name: 'Agência PRO ERP', category: 'Agência', short_description: 'Gerenciador completo de jobs, contratos, faturamento e times de marketing.', long_description: 'O ERP definitivo para agências digitais que querem escalar.', price: 497, rating: 4.75, sales_count: 432, badge: 'MAIS VENDIDO', features: ['Time-tracking e produtividade por funcionário','Aprovação de criativos online pelo cliente','Módulo financeiro com conciliação automática','Pipeline de vendas (CRM) integrado','Geração de relatórios de tráfego e metas'], tech_stack: ['Vue.js','Laravel','MySQL','TailwindCSS','Docker'], gradient: 'from-amber-500/20 via-orange-600/30 to-brand-black', icon_name: 'Briefcase', active: true },
  { slug: 'odonto-pro', name: 'Odonto PRO', category: 'CRM', short_description: 'CRM especializado com odontograma interativo e histórico do paciente.', long_description: 'Um sistema moderno de gestão de consultórios odontológicos.', price: 299, rating: 4.85, sales_count: 512, badge: null, features: ['Odontograma interativo gráfico','Gestão de orçamentos e parcelamentos','Envio automático de lembretes e pós-operatórios','Armazenamento seguro de exames radiográficos','Controle de laboratórios parceiros'], tech_stack: ['React','TypeScript','Node.js','PostgreSQL','AWS S3'], gradient: 'from-sky-500/20 via-indigo-600/30 to-brand-black', icon_name: 'Smile', active: true },
  { slug: 'fusion-ai', name: 'Fusion AI Chatbot', category: 'IA', short_description: 'Agente inteligente treinado com seus dados para suporte e vendas 24/7.', long_description: 'Alimente o Fusion AI com o PDF da sua empresa, site ou manuais e tenha um agente inteligente super-treinado.', price: 397, rating: 4.92, sales_count: 887, badge: 'IA', features: ['Treinamento simples por upload de arquivos','Transição fluida de IA para humano','Integração multicanal oficial e não-oficial','Integrações com CRMs externos via API','Estatísticas detalhadas de sentimento de chat'], tech_stack: ['React','Next.js','Python','FastAPI','LangChain','Pinecone'], gradient: 'from-purple-600/25 via-indigo-600/30 to-brand-black', icon_name: 'Cpu', active: true },
  { slug: 'local-leads-pro', name: 'Local Leads PRO', category: 'Automação', short_description: 'Extrator automático de leads locais com informações completas do Google Maps.', long_description: 'Encontre milhares de clientes B2B em segundos.', price: 147, rating: 4.7, sales_count: 1650, badge: 'MAIS VENDIDO', features: ['Busca ilimitada de empresas por palavra-chave','Extração de contatos (e-mail, telefone, redes)','Exportação fácil para CSV / Excel','Verificador de WhatsApp ativo automático','Sistema anti-bloqueio integrado'], tech_stack: ['Electron','React','Puppeteer','TypeScript','Node.js'], gradient: 'from-yellow-600/20 via-amber-600/30 to-brand-black', icon_name: 'Search', active: true },
  { slug: 'maquina-pro', name: 'Máquina PRO Vendas', category: 'Automação', short_description: 'Módulo de prospecção fria automatizada multicanal (LinkedIn, E-mail e Zap).', long_description: 'Estruture uma máquina automática de prospecção ativa.', price: 247, rating: 4.8, sales_count: 940, badge: 'HOT', features: ['Fluxo de cadência visual sequencial','Automação de ações de conta no LinkedIn','Spam filter prevention para e-mails','Integração com Hubspot e ActiveCampaign','Painel de conversões e respostas'], tech_stack: ['Node.js','React','PostgreSQL','TailwindCSS','RabbitMQ'], gradient: 'from-orange-600/25 via-red-700/30 to-brand-black', icon_name: 'Zap', active: true },
  { slug: 'finance-pro', name: 'Finance PRO Dashboard', category: 'Financeiro', short_description: 'Plataforma para gestão financeira empresarial com DRE, fluxo de caixa e conciliação.', long_description: 'Monitore a saúde financeira do seu negócio em tempo real.', price: 289, rating: 4.9, sales_count: 730, badge: 'NOVO', features: ['Importação automática de arquivos OFX','Relatórios contábeis DRE e Balanço customizados','Controle de contas a pagar e receber com alertas','Integração com bancos via Open Finance','Exportação simplificada para o contador'], tech_stack: ['Next.js','Python','PostgreSQL','TailwindCSS','Chart.js'], gradient: 'from-emerald-500/20 via-teal-600/30 to-brand-black', icon_name: 'TrendingUp', active: true },
  { slug: 'dashboard-pro', name: 'Dashboard Admin PRO', category: 'Dashboard', short_description: 'Template administrativo Next.js / React ultra moderno com componentes prontos.', long_description: 'Poupe centenas de horas de desenvolvimento com a estrutura definitiva de dashboard.', price: 97, rating: 4.88, sales_count: 1890, badge: 'MAIS VENDIDO', features: ['100+ componentes de UI personalizáveis','Dark Mode e Light Mode nativos e configurados','Integração fácil com NextAuth e JWT','Design baseado no Figma oficial incluso','Atualizações vitalícias sem custos'], tech_stack: ['Next.js','TypeScript','TailwindCSS','Framer Motion','Recharts'], gradient: 'from-violet-600/20 via-purple-600/30 to-brand-black', icon_name: 'Layout', active: true },
  { slug: 'crm-pro', name: 'CRM PRO Pipeline', category: 'CRM', short_description: 'Gestão visual de oportunidades, metas comerciais e histórico de clientes.', long_description: 'Coloque ordem na sua equipe comercial.', price: 199, rating: 4.78, sales_count: 840, badge: null, features: ['Múltiplos funis de vendas ilimitados','Integração automática com formulários web','Histórico unificado com linha do tempo','Notificações em tempo real no Telegram/Slack','Previsão de vendas automatizada'], tech_stack: ['React','NestJS','PostgreSQL','TypeScript','Redis'], gradient: 'from-indigo-600/25 via-blue-700/30 to-brand-black', icon_name: 'UserCheck', active: true },
  { slug: 'ultra-zap', name: 'Ultra Zap Automações', category: 'WhatsApp', short_description: 'Ferramenta avançada para envios em lote e rotas de aquecimento de chips.', long_description: 'Reduza drasticamente o risco de bloqueio ao prospectar no WhatsApp.', price: 159, rating: 4.82, sales_count: 1045, badge: 'HOT', features: ['Aquecedor de chips automático integrado','Rotação inteligente de múltiplos remetentes','Relatórios e métricas de entregabilidade','Validador de listas de números ativos','Envio de mídias de forma nativa'], tech_stack: ['Node.js','Express','React','Puppeteer','TailwindCSS'], gradient: 'from-green-600/20 via-teal-600/30 to-brand-black', icon_name: 'Zap', active: true },
  { slug: 'saas-delivery', name: 'SaaS Delivery Multi-Tenant', category: 'SaaS', short_description: 'Plataforma completa para você vender assinaturas de cardápio digital whitelabel.', long_description: 'Monte seu próprio negócio bilionário de delivery.', price: 799, rating: 4.94, sales_count: 310, badge: 'MAIS VENDIDO', features: ['Subdomínios automáticos para cada lojista','Gateway de assinatura recorrente nativo','Configuração fácil de logo e marca (White Label)','Painel geral do administrador de alta performance','Banco de dados multi-tenant isolado'], tech_stack: ['Laravel','Vue.js','MySQL','Inertia.js','Stripe API'], gradient: 'from-red-600/20 via-orange-600/30 to-brand-black', icon_name: 'Grid', active: true },
  { slug: 'auto-lead-ia', name: 'Auto Lead IA', category: 'IA', short_description: 'Agente autônomo que escreve e-mails de vendas hiper-personalizados.', long_description: 'Esqueça os e-mails frios genéricos.', price: 297, rating: 4.9, sales_count: 520, badge: 'IA', features: ['Escaneador inteligente de URL do lead','Escrita de e-mails hiper-personalizados com IA','Sistema de testes A/B integrados','Rastreamento de aberturas e cliques','Cadência automática com gatilhos de atraso'], tech_stack: ['Python','Django','React','OpenAI GPT-4','PostgreSQL'], gradient: 'from-pink-600/20 via-purple-700/30 to-brand-black', icon_name: 'Mail', active: true },
  { slug: 'zapbot-web', name: 'ZapBot Builder Web', category: 'WhatsApp', short_description: 'Painel visual de arrastar e soltar para criar fluxos de conversa automáticos.', long_description: 'Um editor de fluxo do tipo no-code idêntico ao Typebot.', price: 189, rating: 4.87, sales_count: 780, badge: 'NOVO', features: ['Editor visual no-code arrastar e soltar','Integração simples com Google Sheets','Integração nativa com ChatGPT API','Envio de áudio simulando gravação em tempo real','Controle e estatísticas de engajamento do funil'], tech_stack: ['React','TypeScript','Node.js','PostgreSQL','TailwindCSS'], gradient: 'from-green-500/20 via-emerald-600/30 to-brand-black', icon_name: 'GitFork', active: true },
  { slug: 'mindmap-ai', name: 'MindMap AI', category: 'IA', short_description: 'Criação instantânea de mapas mentais e organogramas a partir de prompts simples.', long_description: 'Organize suas ideias ou crie planos de estudo com velocidade recorde.', price: 129, rating: 4.76, sales_count: 450, badge: 'IA', features: ['Geração inteligente a partir de prompts ou PDFs','Editor manual de nós interativo e colorido','Exportação para PDF, PNG, SVG e markdown','Colaboração em equipe em tempo real','Módulo de apresentação nativo'], tech_stack: ['React','TypeScript','ReactFlow','Python','TailwindCSS'], gradient: 'from-fuchsia-600/20 via-purple-700/30 to-brand-black', icon_name: 'Network', active: true },
  { slug: 'taskflow-saas', name: 'TaskFlow Planner', category: 'SaaS', short_description: 'Gestão visual de projetos com faturamento dinâmico por hora trabalhada.', long_description: 'Gerencie projetos complexos com mais clareza.', price: 349, rating: 4.8, sales_count: 395, badge: null, features: ['Visualização Kanban, Lista e Gantt interativos','Time-tracker com extensão desktop inclusa','Geração automática de invoices de horas extras','Portal exclusivo para clientes externos acompanharem','Integração com Slack e GitHub'], tech_stack: ['Next.js','TypeScript','Node.js','PostgreSQL','TailwindCSS'], gradient: 'from-indigo-600/20 via-blue-700/30 to-brand-black', icon_name: 'Clock', active: true },
  { slug: 'invoicer-pro', name: 'Invoicer Automações', category: 'Financeiro', short_description: 'Emissão automática de notas fiscais de serviço e recibos de vendas integrados.', long_description: 'Acabe com o trabalho manual de emitir notas.', price: 249, rating: 4.72, sales_count: 489, badge: null, features: ['Integração direta com 1200+ prefeituras brasileiras','Suporte para emissão agendada ou no checkout','Envio automático do PDF da nota por e-mail','Dashboards fiscais com tributação mensal simulada','Configuração simplificada Whitelabel'], tech_stack: ['Node.js','Express','React','MongoDB','AWS Lambda'], gradient: 'from-emerald-600/20 via-green-600/30 to-brand-black', icon_name: 'FileText', active: true },
  { slug: 'real-estate-saas', name: 'Imobiliária PRO SaaS', category: 'SaaS', short_description: 'Sistema completo whitelabel para gestão de imóveis, corretores e propostas.', long_description: 'Uma plataforma definitiva para imobiliárias e corretores independentes.', price: 449, rating: 4.83, sales_count: 280, badge: 'HOT', features: ['Catálogo interativo com filtros geográficos avançados','Gestão de comissões por corretores parceiros','Ficha de visitas em formato digital legal','Integração rápida para portais como Zap Imóveis','Painel intuitivo de propostas e contratos'], tech_stack: ['React','Laravel','MySQL','TailwindCSS','Google Maps API'], gradient: 'from-blue-600/20 via-cyan-600/30 to-brand-black', icon_name: 'Home', active: true },
  { slug: 'academify', name: 'Academify LMS', category: 'Landing Pages', short_description: 'Plataforma moderna de infoprodutos com área de membros estilo Netflix.', long_description: 'Ofereça uma experiência premium e viciante para seus alunos.', price: 299, rating: 4.96, sales_count: 620, badge: 'MAIS VENDIDO', features: ['Layout premium no estilo streaming (Netflix style)','Player de vídeo nativo criptografado anti-pirataria','Sistema completo de gamificação e conquistas','Módulo de fórum integrado por aula','Emissão automática de certificados modernos'], tech_stack: ['Next.js','Node.js','PostgreSQL','TailwindCSS','Mux Video'], gradient: 'from-violet-600/20 via-purple-700/30 to-brand-black', icon_name: 'PlayCircle', active: true },
  { slug: 'leadhunter', name: 'LeadHunter Agent', category: 'Automação', short_description: 'Robô inteligente que mapeia e-mails e contatos comerciais via redes sociais.', long_description: 'Identifique tomadores de decisão em empresas corporativas de forma rápida.', price: 179, rating: 4.68, sales_count: 899, badge: null, features: ['Filtro dinâmico por cargos e localizações','Sistema avançado de validação de e-mails','Integração direta com o Máquina PRO e CRM PRO','Configuração fácil de rotinas de coleta','Relatórios com estatísticas de mercado'], tech_stack: ['Node.js','Python','React','MongoDB','Puppeteer'], gradient: 'from-amber-600/20 via-orange-600/30 to-brand-black', icon_name: 'UserPlus', active: true },
  { slug: 'botpress-pro', name: 'BotPress Pro IA', category: 'IA', short_description: 'Construtor de agentes virtuais inteligentes integrados ao ChatGPT e Claude API.', long_description: 'Construa chatbots ultra inteligentes capazes de raciocinar e agir.', price: 379, rating: 4.9, sales_count: 460, badge: 'IA', features: ['Execução de funções API nativas no chatbot','Treinamento híbrido usando IA e regras base','Logs avançados de chamadas e consumo de tokens','Configuração simplificada multi-idiomas','Templates de fluxos de checkout automático'], tech_stack: ['React','TypeScript','Node.js','LangChain','OpenAI / Claude API'], gradient: 'from-purple-600/25 via-pink-700/30 to-brand-black', icon_name: 'MessageCircle', active: true },
  { slug: 'webscraper-ai', name: 'WebScraper AI Extrações', category: 'Automação', short_description: 'Extrator de dados da web visual no-code impulsionado por IA para contornar Captchas.', long_description: 'Colete dados estruturados de qualquer e-commerce ou portal de notícias.', price: 197, rating: 4.81, sales_count: 670, badge: 'NOVO', features: ['Reconhecimento inteligente de tabelas de dados','Proxy rotativo residencial incluso por padrão','Resolução automática de captchas difíceis','Exportador para planilhas e banco de dados via API','Agendador de extrações automáticas recorrentes'], tech_stack: ['React','TypeScript','Python','Scrapy','Selenium','AWS'], gradient: 'from-yellow-600/20 via-amber-700/30 to-brand-black', icon_name: 'Database', active: true },
  { slug: 'support-desk', name: 'Support Desk Whitelabel', category: 'CRM', short_description: 'Sistema completo para gestão de chamados com base de conhecimento integrada.', long_description: 'Melhore o atendimento ao cliente e reduza chamados repetitivos.', price: 299, rating: 4.76, sales_count: 390, badge: null, features: ['Gestão de tickets por prioridade e categorias','Base de conhecimento pesquisável estilo Google','Módulo de chat em tempo real personalizável','Pesquisa de satisfação NPS integrada pós-atendimento','Configuração de domínios personalizados para lojistas'], tech_stack: ['React','TypeScript','Node.js','PostgreSQL','TailwindCSS'], gradient: 'from-blue-600/20 via-indigo-600/30 to-brand-black', icon_name: 'HelpCircle', active: true },
  { slug: 'easy-billing', name: 'Easy Billing Assinaturas', category: 'Financeiro', short_description: 'Gerenciador de cobranças recorrentes, assinaturas e recuperação por WhatsApp.', long_description: 'Aumente o faturamento recorrente do seu negócio reduzindo a inadimplência.', price: 269, rating: 4.85, sales_count: 512, badge: 'HOT', features: ['Geração de faturas e links de pagamento simples','Lembretes de cobrança automáticos por WhatsApp','Gestão de re-tentativa de cobrança inteligente','Suporte para múltiplos planos e cupons de desconto','Relatório detalhado de MRR e Churn Rate'], tech_stack: ['Next.js','Node.js','PostgreSQL','Stripe & Asaas APIs','TailwindCSS'], gradient: 'from-emerald-500/20 via-green-600/30 to-brand-black', icon_name: 'CreditCard', active: true },
  { slug: 'smart-analytics', name: 'Smart Analytics Pro', category: 'Dashboard', short_description: 'Estatísticas e análise de tráfego de sites focada em privacidade, alternativa ao GA4.', long_description: 'Uma ferramenta leve e elegante para analisar o tráfego dos seus sites.', price: 149, rating: 4.91, sales_count: 710, badge: 'NOVO', features: ['Script de monitoramento ultra leve (<2kb)','Sem conformidade chata de cookies (100% GDPR)','Acompanhamento de conversão de metas em tempo real','Mapas de calor de cliques de usuários na página','Relatórios automáticos enviados por e-mail/Telegram'], tech_stack: ['React','ClickHouse','Node.js','TypeScript','TailwindCSS'], gradient: 'from-violet-600/20 via-pink-700/30 to-brand-black', icon_name: 'BarChart', active: true },
  { slug: 'social-planner', name: 'Social Planner AI', category: 'Agência', short_description: 'Agendador de publicações integrado a um redator de posts de IA automatizado.', long_description: 'Mantenha suas redes sociais movimentadas sem esforço diário.', price: 199, rating: 4.74, sales_count: 580, badge: 'IA', features: ['Geração inteligente de textos e imagens conceituais','Calendário visual de publicações no modelo arrastar e soltar','Aprovação prévia de publicações simplificada','Relatório unificado de alcance e engajamento','Suporte para múltiplos perfis corporativos'], tech_stack: ['React','Node.js','MongoDB','OpenAI & Midjourney APIs','TailwindCSS'], gradient: 'from-amber-600/20 via-orange-600/30 to-brand-black', icon_name: 'Calendar', active: true },
  { slug: 'ecom-engine', name: 'E-com Engine Whitelabel', category: 'E-commerce', short_description: 'Código-fonte pronto para loja virtual premium com checkout integrado de um clique.', long_description: 'Monte uma loja virtual premium em minutos.', price: 349, rating: 4.88, sales_count: 460, badge: null, features: ['Checkout de uma página ultra otimizado','Suporte para variações complexas de produtos','Cálculo de frete em tempo real (Correios/Melhor Envio)','Integração simples com Pixel do Facebook e TikTok','Painel de cupons de descontos e promoções em lote'], tech_stack: ['Next.js','Node.js','PostgreSQL','TailwindCSS','Prisma'], gradient: 'from-blue-600/20 via-indigo-700/30 to-brand-black', icon_name: 'ShoppingBag', active: true },
  { slug: 'landing-convert', name: 'Landing Pack Neon', category: 'Landing Pages', short_description: 'Pacote com 10 templates de Landing Pages de alta conversão no estilo dark mode premium.', long_description: 'Uma coleção de templates HTML/React prontos e editáveis.', price: 89, rating: 4.93, sales_count: 1490, badge: 'MAIS VENDIDO', features: ['10 designs exclusivos focados em nichos de alta renda','Desenvolvido com código limpo em React e TailwindCSS','Estruturas prontas de formulário com validação inclusa','Animações suaves e responsividade nativa completa','Arquivos originais do Figma para ajustes inclusos'], tech_stack: ['React','TypeScript','TailwindCSS','Framer Motion'], gradient: 'from-orange-600/25 via-brand-neonOrange/30 to-brand-black', icon_name: 'FileCode', active: true },
  { slug: 'cyber-auth', name: 'Cyber Auth Boilerplate', category: 'Landing Pages', short_description: 'Módulo de autenticação segura e registro com 2FA e login social integrado.', long_description: 'Não perca tempo configurando sistemas de login.', price: 79, rating: 4.79, sales_count: 920, badge: 'NOVO', features: ['Integração rápida com NextAuth, Firebase ou JWT','Telas de registro e login com design premium inclusas','Autenticação multifator (2FA) nativa configurada','Configuração simplificada de envio de e-mails transacionais','Módulo de controle de acessos por papéis (RBAC)'], tech_stack: ['React','TypeScript','NextAuth','TailwindCSS','Prisma'], gradient: 'from-cyan-600/20 via-blue-700/30 to-brand-black', icon_name: 'ShieldAlert', active: true },
  { slug: 'multitenant-base', name: 'Next SaaS Boilerplate', category: 'SaaS', short_description: 'Estrutura base multi-tenant para novos projetos SaaS com planos e Stripe integrados.', long_description: 'Acelere o lançamento do seu produto.', price: 497, rating: 4.97, sales_count: 380, badge: 'HOT', features: ['Isolamento completo de banco de dados (Multitenancy)','Integração completa com Stripe Billing (Checkout/Assinaturas)','Design do painel principal responsivo e moderno','Autenticação segura JWT com sessões persistentes','Infraestrutura para domínios próprios de lojistas'], tech_stack: ['Next.js','TypeScript','TailwindCSS','Prisma','Stripe','Docker'], gradient: 'from-violet-600/25 via-indigo-700/30 to-brand-black', icon_name: 'Box', active: true },
  { slug: 'seo-boost-ia', name: 'SEO Boost IA Escritor', category: 'IA', short_description: 'Ferramenta de criação de artigos de blog otimizados e prontos para ranquear no Google.', long_description: 'Escreva conteúdos que geram cliques reais no buscador.', price: 199, rating: 4.84, sales_count: 615, badge: 'IA', features: ['Pesquisa de palavras-chave integrada via APIs SEO','Escrita assistida por Inteligência Artificial avançada','Verificador de legibilidade e densidade de palavras-chave','Integração direta com o WordPress e Webflow','Monitor automático de posições no ranking de pesquisas'], tech_stack: ['React','Python','PostgreSQL','OpenAI API','TailwindCSS'], gradient: 'from-purple-600/20 via-pink-600/30 to-brand-black', icon_name: 'PenTool', active: true },
  { slug: 'stock-manager', name: 'Stock Manager ERP', category: 'E-commerce', short_description: 'ERP para controle de estoque físico e digital com alertas de reposição inteligente.', long_description: 'Mantenha seu inventário em perfeito alinhamento.', price: 229, rating: 4.7, sales_count: 412, badge: null, features: ['Integração multi-lojas e controle centralizado','Painel de previsão inteligente de compras por histórico','Geração e leitura fácil de etiquetas com código de barras','Relatórios e gráficos de giro de estoque por produto','Módulo de devoluções e trocas de mercadoria'], tech_stack: ['React','Node.js','PostgreSQL','TailwindCSS','Express'], gradient: 'from-blue-600/20 via-cyan-600/30 to-brand-black', icon_name: 'Package', active: true },
  { slug: 'voiceagent-ai', name: 'VoiceAgent AI Chamadas', category: 'IA', short_description: 'Agente de voz inteligente por telefone para qualificação de leads e suporte básico.', long_description: 'Automatize suas ligações de qualificação comercial de forma impressionante.', price: 497, rating: 4.93, sales_count: 290, badge: 'IA', features: ['Síntese de voz hiper-realista com baixa latência','Integração de agenda via Google Calendar','Transcrição instantânea e gravação de chamadas','Criação de roteiros interativos estruturados por árvore','Conexão com plataformas Twilio e Vonage'], tech_stack: ['Node.js','Python','Twilio API','Vapi / ElevenLabs','MongoDB'], gradient: 'from-fuchsia-600/20 via-purple-700/30 to-brand-black', icon_name: 'PhoneCall', active: true },
  { slug: 'email-blast', name: 'Email Blast Marketing', category: 'Automação', short_description: 'Envio em massa de e-mail marketing com alta entregabilidade via SMTP próprio.', long_description: 'Crie campanhas de e-mail marketing sem pagar fortunas por volume de envios.', price: 139, rating: 4.78, sales_count: 805, badge: 'NOVO', features: ['Editor visual de e-mails responsivos (Mosaico)','Higienizador automático de listas (remove e-mails falsos)','Conexão ilimitada com múltiplos provedores SMTP','Módulo avançado de automação por cliques/aberturas','Formulários e popups de captura inclusos'], tech_stack: ['React','Go','PostgreSQL','TailwindCSS','Redis'], gradient: 'from-orange-600/20 via-red-600/30 to-brand-black', icon_name: 'Send', active: true },
  { slug: 'legal-docs', name: 'LegalDocs Assinaturas', category: 'Financeiro', short_description: 'Plataforma completa para assinatura digital e gestão de documentos jurídicos.', long_description: 'Assine contratos e propostas com validade jurídica completa.', price: 199, rating: 4.82, sales_count: 540, badge: null, features: ['Assinatura eletrônica e digital com validade legal','Envio fácil de links de assinatura via WhatsApp/E-mail','Criação de templates reutilizáveis de contratos','Armazenamento criptografado na AWS com backup redundante','Notificações de pendências automáticas'], tech_stack: ['React','TypeScript','Node.js','PostgreSQL','Criptografia SHA-256'], gradient: 'from-emerald-500/20 via-teal-600/30 to-brand-black', icon_name: 'CheckSquare', active: true },
  { slug: 'fitness-saas', name: 'Fitness PRO Manager', category: 'SaaS', short_description: 'Sistema completo para academias, estúdios de pilates e personal trainers.', long_description: 'Gerencie treinos, avaliações físicas e mensalidades em um só lugar.', price: 297, rating: 4.75, sales_count: 330, badge: null, features: ['Montador visual de fichas de treino com biblioteca','Aplicativo web responsivo otimizado para o aluno','Gestão de mensalidades com faturamento Pix automático','Módulo de avaliação física (anamnese, composição)','Painel de controle financeiro do estúdio'], tech_stack: ['React','TypeScript','Node.js','MySQL','TailwindCSS'], gradient: 'from-blue-600/20 via-indigo-700/30 to-brand-black', icon_name: 'Heart', active: true },
  { slug: 'cloud-backup', name: 'Cloud Backup Agent', category: 'Automação', short_description: 'Módulo automático para backups incrementais de bancos de dados e arquivos.', long_description: 'Garanta a segurança dos dados do seu negócio sem esforço.', price: 119, rating: 4.86, sales_count: 680, badge: 'NOVO', features: ['Backups incrementais e diferenciais automáticos','Criptografia de arquivos ponta a ponta antes do envio','Suporte para as principais nuvens do mercado','Alertas de falha ou sucesso no Telegram e e-mail','Interface simples de restauração em um clique'], tech_stack: ['Node.js','Go','SQLite','Criptografia AES-256','Shell Script'], gradient: 'from-amber-600/20 via-orange-600/30 to-brand-black', icon_name: 'CloudLightning', active: true },
  { slug: 'dev-boilerplate', name: 'Dev Boilerplate Express', category: 'Dashboard', short_description: 'Template inicial React + Node.js estruturado com infraestrutura e deploy configurados.', long_description: 'Pule a configuração chata de infraestrutura para novas aplicações.', price: 147, rating: 4.9, sales_count: 890, badge: 'MAIS VENDIDO', features: ['Arquitetura Limpa (Clean Architecture) estruturada','Docker Compose e ambiente local pronto','Pipeline de deploy configurado para GitHub Actions','Suíte de testes configurada com Vitest/Jest','Módulo básico de autenticação e logs embutido'], tech_stack: ['React','Node.js','TypeScript','Vitest','Docker','GitHub Actions'], gradient: 'from-violet-600/20 via-indigo-600/30 to-brand-black', icon_name: 'Code', active: true },
  { slug: 'chatbot-multicanal', name: 'Multicanal Chatbot SaaS', category: 'WhatsApp', short_description: 'Atendimento integrado conectando WhatsApp, direct do Instagram, Telegram e chat web.', long_description: 'Centralize todos os canais de comunicação com o cliente em uma única tela.', price: 399, rating: 4.88, sales_count: 420, badge: 'HOT', features: ['Centralização de WhatsApp, Instagram, Telegram e Chat Web','Módulo de chatbot interno por setor de atendimento','Acompanhamento de métricas de tempo de resposta da equipe','Faturamento recorrente Whitelabel integrado para revendedores','API aberta para conexões com outros sistemas'], tech_stack: ['React','TypeScript','Node.js','Redis','Socket.io','MySQL'], gradient: 'from-green-600/20 via-emerald-600/30 to-brand-black', icon_name: 'Share2', active: true }
];

async function main() {
  try {
    console.log('Conectando ao Supabase...');
    await client.connect();
    console.log('Conectado!');

    // 1. Criar tabelas
    console.log('\n[1/5] Criando tabelas...');
    await client.query(`
      create table if not exists products (
        id uuid primary key default gen_random_uuid(),
        slug text unique not null,
        name text not null,
        category text not null,
        short_description text,
        long_description text,
        price numeric not null,
        rating numeric default 5.0,
        sales_count integer default 0,
        badge text,
        features jsonb default '[]'::jsonb,
        tech_stack jsonb default '[]'::jsonb,
        gradient text,
        icon_name text,
        image_url text,
        active boolean default true,
        created_at timestamp with time zone default timezone('utc', now()),
        updated_at timestamp with time zone default timezone('utc', now())
      );

      create table if not exists admin_users (
        user_id uuid primary key,
        email text not null,
        role text default 'super_admin',
        created_at timestamp with time zone default timezone('utc', now())
      );
    `);
    console.log('✅ Tabelas criadas!');

    // 2. Ativar RLS
    console.log('\n[2/5] Configurando RLS...');
    await client.query(`
      alter table products enable row level security;
      alter table admin_users enable row level security;

      drop policy if exists "Produtos ativos são públicos" on products;
      create policy "Produtos ativos são públicos"
        on products for select
        using (active = true);

      drop policy if exists "Somente admins podem gerenciar produtos" on products;
      create policy "Somente admins podem gerenciar produtos"
        on products for all
        using (
          exists (select 1 from admin_users where admin_users.user_id = auth.uid())
        )
        with check (
          exists (select 1 from admin_users where admin_users.user_id = auth.uid())
        );

      drop policy if exists "Admin pode ler seu próprio registro" on admin_users;
      create policy "Admin pode ler seu próprio registro"
        on admin_users for select
        using (user_id = auth.uid());
    `);
    console.log('✅ RLS configurado!');

    // 3. Seed dos produtos
    console.log('\n[3/5] Inserindo produtos...');
    for (const p of PRODUCTS) {
      await client.query(
        `insert into products (slug,name,category,short_description,long_description,price,rating,sales_count,badge,features,tech_stack,gradient,icon_name,active)
         values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
         on conflict (slug) do update set
           name=excluded.name, price=excluded.price, updated_at=now()`,
        [p.slug, p.name, p.category, p.short_description, p.long_description, p.price, p.rating, p.sales_count, p.badge, JSON.stringify(p.features), JSON.stringify(p.tech_stack), p.gradient, p.icon_name, p.active]
      );
      process.stdout.write('.');
    }
    console.log(`\n✅ ${PRODUCTS.length} produtos inseridos!`);

    console.log('\n✅ SETUP COMPLETO! Banco de dados configurado com sucesso.');
  } catch (err) {
    console.error('Erro:', err.message);
  } finally {
    await client.end();
  }
}

main();
